/*
 * File: app/controller/MyMainController.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MySliderMenuApp.controller.MyMainController', {
    extend: 'Ext.app.Controller',

    config: {
        refs: {
            myMainContentContainer: 'container#myMainContainer',
            myNewsContainer: 'container#myNewsContainer'
        },

        control: {
            "button#mybutton": {
                tap: 'navButtonTap'
            },
            "button#mybutton1": {
                tap: 'fbButtonTap'
            }
        }
    },

    navButtonTap: function(button, e, eOpts) {

        var me = this;

        console.log(me.getMyMainContentContainer());

        me.getMyMainContentContainer().setActiveItem('#myFacebookContainer');

    },

    fbButtonTap: function(button, e, eOpts) {
        // this.toggleNavigation (button,e,eOpts);

    }

});